baseURL: "https://behnazj.github.io/" 
title: Dr. Behnaz Jarrahi
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3 

params:
    description: "I am a brain scientist and philosopher of mind."
    author: Name
    googleAnalyticsID: "G-WDNCFJ7MSL"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Behnaz Jarrahi
          subtitle: "I study the human brain using neuroimaging and neuropsychological techniques. I explore the mysteries of the mind through a Philosophical Lens. I have conducted postdoctoral research at the UCLA Semel Institute for Neuroscience and the Stanford School of Medicine."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Dr. Behnaz Jarrahi
          buttons:
            - name: School
              url: https://med.stanford.edu/profiles/behnaz-jarrahi
            - name: LinkedIn
              url: https://www.linkedin.com/in/behnaz-jarrahi

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dr. Behnaz Jarrahi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
